services:
    deadromeo.allowedext.listener:
        class: deadromeo\allowedext\event\listener
        arguments:
            - '@dbal.conn'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener } 
